const appConfig = {
    ADMIN_BASE_URL: '/superadmin',
    FLEET_BASE_URL: '/user',
    FLEET_LOGIN_URL: '/user/fleet',
    DRIVER_BASE_URL: '/driver',
    LOGIN:'/login',
    GOOGLE_LOGIN:'/google/login',
    FACEBOOK_LOGIN:'/facebook/login',
    REGISTER:'/register',
    PROFILE:'/profile',
    UPLOAD:'/upload',
    FORGOT_PASSWORD:'/forget-password',
    SET_PASSWORD:'/set-password',
    VERIFY_OTP:'/verify-otp',
    INVITE_DRIVER:"/invite",
    VIDEOS:"/videos",
    FILTER_VIDEO:"/videos/filter",
    DRIVERS:"/list/drivers",
    CREATE_DRIVER:"/create-user",
    EDIT_DRIVER:"/edit",
    DRIVER_DETAIL:"/detail",
    NOTIFICATIONS:"/notification",
    TICKETS:"/tickets",
    TICKET:"/ticket",
    APPROVE:"/approve",
    ARCHIVE:"/archive",
    VIDEO:"/video",
  };
  
export default appConfig;